# https://docs.readthedocs.io/en/stable/config-file/v2.html
version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"

sphinx:
  configuration: client/doc/conf.py

formats:
  - pdf

python:
  install:
    - requirements: client/doc/requirements.txt
