language: python
script: 
    - "! rm -rf !(telethon|telethon_generator|LICENSE|MANIFEST.in|README.rst|setup.py) .*"

deploy:
  provider: pypi
  user: 
    secure: "oguVoNVeoWo6EXKVN/TgCK01cwBXhY003cCl0r/A77N4RoIpAfBYXZOspHyWZaa0O5mt2ZFBw7ZljBFK/ixFuI7PpgB+BSGt0NcduxDs9ryCq5QcWFqol8KutAj8xvZ3yNyDPTQhy5ALuZUJD7BvcTucIDy8B5Apt8aujaQqciaoCPs7OIJXUwbtQda6X0fpJj83unZZcEZM4hP5zsRIraH4pyad85sOSQyfo8eJJNLWCH21JDFih7g5S6DEEa/De+l9rSz1tvwsSL/phB7Q9Ut62oS9+nYWM4osTB5LdGc4WIADMlRp+CRJlQJkdUgvdHmyhcujUUjxnZcWvIybt+50K94UJKhs6nVGIuSh5zHegbNlGP67nyleOOwdHMltiR0R8JTG2gtXxesQDk/veWbX7E2A4LpJxr112G25MikpTOeBEZWBQDz5gk4EWYXzgxGOP0ty9Ek4MriCwrJ4rNVZ2OPXj1hxM3h0aU1Lk5G+46RpOQrW+nP+7z75/9j3ONt12Ki7IjWqNdS9uRKuIBqdeL8TpJEfgxOk9pLEtaNsX9FORK9FQ6SWJdX9kQeB/I3WziuDQkZ+UQSEwCTk14pmXZeGrjoTSqu3W9GSBSGW09L/5FFWrhnVEPf7czKaa6zxv2M4uyXc/fR9YBSgF0/7h87T1cDEpguE5Ofu3zI="
  password: 
    secure: "CzSzXkr+6kzQkbUEevulEg2ODp5bWd0ARo/wDvNbKFIjYcWZa+hKBhwxeBoCbbhlZYISF6yWzvymDLzdJn/Ryp/yV76UbxoKgQC6KoU8iGGXDDflTRfn9aPmLRdsvDOUBo43xs6UhNdVf7kcjIKdoPfLvynkSjK7Nuh35AuXbv4WDd1N+oyWHNr4s0lH328/VDNlgTZW1BjndZMwwLxB6LHssHqt6R3SCuHZ07VK8Q8ltCHyPa8KtSbyyvUjB21epvpQvxZrzBPslWO6mMfBQ73BAvhWtDHbgXsoJiB2GawbN1QIzHphOmf9V2yy5Zxrum0gp+JhorQjHJiyUM3Qf4ORxvsSsExlEhcQyJBquSKEielL9cVtJ/1ulcNaKc1WxsIe5twhZZRg6pTMTazyCMf5xGBb3LpBcfLzWzHjmpGL0jbD/OEnzwVR9E0RtJeZxYiQaoxwdrVzRlsHm81NTctgvaI7XJaP/3mvDXHsRlaLBJzIAazef/pogeTzSuQL7b0XydTXgKBNqB4lFAHOH56ttN8s6hrMkAvo4CyLeYvIZAHY9EfStqaANQ1gvqBZ04iJNNp6hF1C001ezNOxoaqsRqXit+r5Ndnqzs/tarL9OlFv96ShWBvfCr3CX3ofhrOwlaeePxbUNwayxSN1sHWz3iwZYlwbz0bq0MFaaug="
  on:
    branch: master
  skip_cleanup: true
  