from typing import List

class AES:
    def __init__(self, key: bytes) -> None: ...
    def encrypt(self, plaintext: List[int]) -> List[int]: ...
    def decrypt(self, ciphertext: List[int]) -> List[int]: ...
